var books = [
  { name: "Prakata", ref: "Aktb-01-FRT-001.html" },
  { name: "Penjelasan Penggunaan Bantuan", ref: "Aktb-02-PPB-001.html" },
  { name: "Daptar Singkatan Namo Kitab", ref: "Aktb-03-FRT-2-001.html" },
  { name: "Asal Mulo Dunio", ref: "Aktb-04-GEN-001.html" },
  { name: "Ester", ref: "Aktb-05-EST-001.html" },
  { name: "Saér Nyanyian", ref: "Aktb-06-PSA-001.html" },
  { name: "Yunus", ref: "Aktb-07-JON-001.html" },
  { name: "Matius", ref: "Aktb-08-MAT-001.html" },
  { name: "Lukas", ref: "Aktb-09-LUK-001.html" },
  { name: "Yahya", ref: "Aktb-10-JHN-001.html" },
  { name: "Cerito Rosul-Rosul", ref: "Aktb-11-ACT-001.html" },
  { name: "Pilipi", ref: "Aktb-12-PHP-001.html" },
  { name: "1 Yahya", ref: "Aktb-13-1JN-001.html" },
  { name: "2 Yahya", ref: "Aktb-14-2JN-001.html" },
  { name: "3 Yahya", ref: "Aktb-15-3JN-001.html" },
  { name: "Kamus Kato Kunci", ref: "Aktb-16-GLO-001.html" },
  { name: "Pertanyoan Belajar Alkitab", ref: "Aktb-17-DBS-001.html" },
];
